services:
#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     blogger_blog.twig.extension:
            class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
            tags:
                - { name: twig.extension }
     blogger.symblog.admin.blog:
            class: Blogger\BlogBundle\Admin\BlogAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: symblog, label: Blogs }
            arguments: [null, Blogger\BlogBundle\Entity\Blog, BloggerBlogBundle:BlogAdmin]

     blogger.symblog.admin.comment:
            class: Blogger\BlogBundle\Admin\CommentAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: symblog, label: Comments }
            arguments: [null, Blogger\BlogBundle\Entity\Comment, BloggerBlogBundle:CommentAdmin]
     blogger_user.password_resetting:
             class: Blogger\BlogBundle\EventListener\PasswordResettingListener
             arguments: [@router]
             tags:
                 - { name: kernel.event_subscriber }